# -*- coding: utf-8 -*-
"""DAY4-project 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8LClUUXd5WIhIqklxTIv6XDvjw0TPy-
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

st.set_page_config(page_title="Customer Segmentation using K-Means", layout="wide")

st.title("📊 Customer Segmentation using K-Means Clustering")

# Load dataset
df = pd.read_csv("/content/income.csv")

st.subheader("Dataset")
st.dataframe(df)

# ----------------------------
# Original Data
# ----------------------------
st.subheader("Original Data")

fig, ax = plt.subplots(figsize=(6,4))
ax.scatter(df["Age"], df["Income($)"], color="blue")
ax.set_xlabel("Age")
ax.set_ylabel("Income ($)")
st.pyplot(fig)

# ----------------------------
# Scaling
# ----------------------------
scaler = MinMaxScaler()

df_scaled = df.copy()

df_scaled["Income($)"] = scaler.fit_transform(df_scaled[["Income($)"]])
df_scaled["Age"] = scaler.fit_transform(df_scaled[["Age"]])

st.subheader("Scaled Data")

fig, ax = plt.subplots(figsize=(6,4))
ax.scatter(df_scaled["Age"], df_scaled["Income($)"], color="orange")
ax.set_xlabel("Scaled Age")
ax.set_ylabel("Scaled Income")
st.pyplot(fig)

# ----------------------------
# Select Number of Clusters
# ----------------------------
st.sidebar.header("Settings")
k = st.sidebar.slider("Select Number of Clusters", 2, 10, 3)

km = KMeans(n_clusters=k, random_state=42)
df_scaled["Cluster"] = km.fit_predict(df_scaled[["Age", "Income($)"]])

# ----------------------------
# Clustered Data
# ----------------------------
st.subheader(f"K-Means Clustering (K = {k})")

colors = [
    "red", "green", "blue", "orange", "purple",
    "brown", "pink", "gray", "cyan", "black"
]

fig, ax = plt.subplots(figsize=(7,5))

for i in range(k):
    cluster = df_scaled[df_scaled["Cluster"] == i]
    ax.scatter(
        cluster["Age"],
        cluster["Income($)"],
        color=colors[i % len(colors)],
        label=f"Cluster {i}"
    )

# Centroids
centers = km.cluster_centers_
ax.scatter(
    centers[:, 0],
    centers[:, 1],
    color="black",
    marker="*",
    s=250,
    label="Centroids"
)

ax.set_xlabel("Scaled Age")
ax.set_ylabel("Scaled Income")
ax.legend()

st.pyplot(fig)

# ----------------------------
# Clustered Dataset
# ----------------------------
st.subheader("Clustered Dataset")
st.dataframe(df_scaled)

# ----------------------------
# Elbow Method
# ----------------------------
st.subheader("Elbow Method")

sse = []

K = range(1, 10)

for i in K:
    model = KMeans(n_clusters=i, random_state=42)
    model.fit(df_scaled[["Age", "Income($)"]])
    sse.append(model.inertia_)

fig, ax = plt.subplots(figsize=(6,4))
ax.plot(K, sse, marker='o')
ax.set_xlabel("Number of Clusters (K)")
ax.set_ylabel("Sum of Squared Error (SSE)")
ax.set_title("Elbow Method")
ax.grid(True)

st.pyplot(fig)

st.success("Clustering completed successfully!")