# -*- coding: utf-8 -*-
"""DAY4-project 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8LClUUXd5WIhIqklxTIv6XDvjw0TPy-
"""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Customer Segmentation",
    page_icon="📊",
    layout="wide"
)

# -----------------------------
# Title
# -----------------------------
st.title("📊 Customer Segmentation using K-Means Clustering")
st.markdown(
    """
This application groups customers based on their **Age** and **Income**
using the **K-Means Clustering** algorithm.
"""
)

st.divider()

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.header("⚙️ Model Settings")

k = st.sidebar.slider(
    "Select Number of Clusters (K)",
    min_value=2,
    max_value=10,
    value=3
)

st.sidebar.markdown("---")

st.sidebar.info(
    """
### About
This project demonstrates:

- K-Means Clustering
- Feature Scaling
- Customer Segmentation
- Elbow Method

**Tech Stack**

- Python
- Pandas
- Scikit-Learn
- Matplotlib
- Streamlit
"""
)

# -----------------------------
# Load Dataset
# -----------------------------
df = pd.read_csv("income.csv")

# -----------------------------
# Dataset Preview
# -----------------------------
st.subheader("📋 Customer Dataset")

st.dataframe(df, use_container_width=True)

col1, col2 = st.columns(2)

with col1:
    st.metric("Total Customers", len(df))

with col2:
    st.metric("Features", len(df.columns))

st.divider()

# -----------------------------
# Original Data Visualization
# -----------------------------
st.subheader("📈 Original Customer Distribution")

fig, ax = plt.subplots(figsize=(6,4))

ax.scatter(
    df["Age"],
    df["Income($)"],
    color="royalblue",
    s=70
)

ax.set_xlabel("Age")
ax.set_ylabel("Income ($)")
ax.set_title("Age vs Income")

st.pyplot(fig)

# -----------------------------
# Feature Scaling
# -----------------------------
scaled_df = df.copy()

scaler = MinMaxScaler()

scaled_df["Age"] = scaler.fit_transform(scaled_df[["Age"]])
scaled_df["Income($)"] = scaler.fit_transform(scaled_df[["Income($)"]])

st.success("✅ Data scaled successfully using MinMaxScaler.")

# -----------------------------
# KMeans Model
# -----------------------------
model = KMeans(n_clusters=k, random_state=42)

scaled_df["Cluster"] = model.fit_predict(
    scaled_df[["Age", "Income($)"]]
)

# -----------------------------
# Cluster Visualization
# -----------------------------
st.subheader("🎯 Customer Clusters")

colors = [
    "red",
    "green",
    "blue",
    "orange",
    "purple",
    "brown",
    "pink",
    "cyan",
    "gray",
    "olive"
]

fig, ax = plt.subplots(figsize=(7,5))

for i in range(k):

    cluster = scaled_df[scaled_df["Cluster"] == i]

    ax.scatter(
        cluster["Age"],
        cluster["Income($)"],
        s=80,
        color=colors[i],
        label=f"Cluster {i+1}"
    )

centers = model.cluster_centers_

ax.scatter(
    centers[:,0],
    centers[:,1],
    marker="*",
    s=300,
    color="black",
    label="Centroids"
)

ax.set_xlabel("Scaled Age")
ax.set_ylabel("Scaled Income")
ax.set_title("K-Means Customer Segmentation")
ax.legend()

st.pyplot(fig)

st.divider()

# -----------------------------
# Clustered Dataset
# -----------------------------
st.subheader("📊 Clustered Dataset")

st.dataframe(scaled_df, use_container_width=True)

# -----------------------------
# Cluster Summary
# -----------------------------
st.subheader("📌 Customers in Each Cluster")

cluster_count = (
    scaled_df["Cluster"]
    .value_counts()
    .sort_index()
)

st.bar_chart(cluster_count)

st.divider()

# -----------------------------
# Elbow Method
# -----------------------------
st.subheader("📉 Elbow Method")

sse = []

K = range(1,11)

for i in K:

    km = KMeans(
        n_clusters=i,
        random_state=42
    )

    km.fit(scaled_df[["Age","Income($)"]])

    sse.append(km.inertia_)

fig, ax = plt.subplots(figsize=(7,4))

ax.plot(
    K,
    sse,
    marker="o",
    linewidth=2
)

ax.set_xlabel("Number of Clusters (K)")
ax.set_ylabel("Sum of Squared Error (SSE)")
ax.set_title("Elbow Method")
ax.grid(True)

st.pyplot(fig)

st.info(
    "The optimal value of K is usually chosen at the 'elbow' point where the SSE starts decreasing more slowly."
)

st.divider()

# -----------------------------
# Footer
# -----------------------------
st.markdown(
    """
---
### 👩‍💻 Project Summary

This project uses the **K-Means Clustering** algorithm to segment customers based on **Age** and **Income**.  
Feature scaling is performed using **MinMaxScaler**, and the **Elbow Method** is used to identify the optimal number of clusters.

**Developed as part of my AI/ML Internship.**
"""
)
